package pl.wj.lotto.domain.ticket.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import pl.wj.lotto.domain.common.drawingtype.DrawingType;
import pl.wj.lotto.domain.common.notification.NotificationPort;
import pl.wj.lotto.domain.common.numbersgenerator.NumbersGeneratorPort;
import pl.wj.lotto.domain.common.numberstemplate.DrawingTimeCheckable;
import pl.wj.lotto.domain.common.numberstemplate.NumbersTemplate;
import pl.wj.lotto.domain.common.numberstemplate.model.LottoNumbers;
import pl.wj.lotto.domain.drawing.port.in.DrawingServicePort;
import pl.wj.lotto.domain.ticket.model.Ticket;
import pl.wj.lotto.domain.ticket.model.dto.TicketRequestDto;
import pl.wj.lotto.domain.ticket.model.dto.TicketResponseDto;
import pl.wj.lotto.domain.ticket.port.out.TicketRepositoryPort;

import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.BDDMockito.given;

@ExtendWith(MockitoExtension.class)
class TicketServiceTest {
    @Mock
    private TicketRepositoryPort ticketRepositoryPort;
    @Mock
    private NotificationPort notificationPort;
    @Mock
    private NumbersGeneratorPort numbersGeneratorPort;
    @Mock
    private DrawingServicePort drawingServicePort;
    @InjectMocks
    private TicketService ticketService;

    @Test
    void shouldAddNewTicketWhenThereIsUserId() {
        // given
        DrawingType drawingType = DrawingType.LOTTO;
        LocalDateTime generationTime = LocalDateTime.now();
        LocalDateTime nextDrawingTime = LocalDateTime.now().plusDays(1);
        String userId = "some-user-id";
        String id = "some-id";
        TicketRequestDto ticketRequestDto = TicketRequestDto.builder()
                .userId(userId)
                .drawingTypeId(drawingType.getId())
                .numberOfDrawings(1)
                .numbersAutogenerated(true)
                .build();
        List<Integer> mainNumbers = List.of(1,2,3,4,5,6);
        NumbersTemplate numbers = new LottoNumbers();
        numbers.setNumbers(mainNumbers, null);
        TicketResponseDto expectedResult = TicketResponseDto.builder()
                .id(id)
                .userId(userId)
                .drawingTypeName(drawingType.getName())
                .numberOfDrawings(1)
                .numbers(numbers)
                .generationTime(generationTime)
                .nextDrawingTime(nextDrawingTime)
                .build();
        given(numbersGeneratorPort.generate(anyInt(), anyInt(), anyInt())).willReturn(mainNumbers);
        given(ticketRepositoryPort.save(any(Ticket.class))).willAnswer(
                i -> {
                    Ticket t = i.getArgument(0, Ticket.class);
                    t.setId(id);
                    t.setGenerationTime(generationTime);
                    return t;
                });
        given(drawingServicePort.getNextDrawingTime(any(DrawingTimeCheckable.class))).willReturn(nextDrawingTime);

        // when
        TicketResponseDto result = ticketService.addTicket(ticketRequestDto);

        // then
        assertThat(result)
                .usingRecursiveComparison()
                .isEqualTo(expectedResult);
    }

}