package pl.wj.lotto.domain.ticket.adapter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import pl.wj.lotto.domain.common.gametype.GameType;
import pl.wj.lotto.domain.common.notification.NotificationPort;
import pl.wj.lotto.domain.common.numbersgenerator.NumbersGeneratorPort;
import pl.wj.lotto.domain.draw.adapter.DrawServiceAdapter;
import pl.wj.lotto.domain.draw.port.in.DrawServicePort;
import pl.wj.lotto.domain.draw.service.DrawService;
import pl.wj.lotto.domain.ticket.mapper.TicketMapper;
import pl.wj.lotto.domain.ticket.model.dto.TicketRequestDto;
import pl.wj.lotto.domain.ticket.model.dto.TicketResponseDto;
import pl.wj.lotto.domain.ticket.port.out.TicketRepositoryPort;
import pl.wj.lotto.domain.ticket.service.TicketService;
import pl.wj.lotto.infrastructure.notification.fake.email.EmailNotificationFakeAdapter;
import pl.wj.lotto.infrastructure.numbergenerator.fake.NumbersGeneratorFakeAdapter;
import pl.wj.lotto.infrastructure.persistence.fake.draw.DrawFakeAdapter;
import pl.wj.lotto.infrastructure.persistence.fake.ticket.TicketFakeAdapter;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class TicketServiceAdapterComponentTest {
    private NotificationPort notificationPort;
    private NumbersGeneratorPort numbersGeneratorPort;
    private TicketRepositoryPort ticketRepositoryPort;
    private DrawServicePort drawServicePort;
    private TicketServiceAdapter ticketServiceAdapter;

    @BeforeEach
    void setUp() {
        notificationPort = new EmailNotificationFakeAdapter();
        ticketRepositoryPort = new TicketFakeAdapter();
        numbersGeneratorPort = new NumbersGeneratorFakeAdapter();
        DrawService drawService = new DrawService(new DrawFakeAdapter());
        drawServicePort = new DrawServiceAdapter(drawService);
        TicketService ticketService = new TicketService(
                ticketRepositoryPort, notificationPort, numbersGeneratorPort, drawServicePort);
        ticketServiceAdapter = new TicketServiceAdapter(ticketService);
    }

    @Test
    void shouldAddNewTicketWhenAnonymousUserHasChosenNumbers() {
        // given
        GameType gameType = GameType.LOTTO;
        List<Integer> mainNumbers = List.of(1,2,3,4,5,6);
        TicketRequestDto ticketRequestDto = TicketRequestDto.builder()
                .userId(null)
                .gameTypeId(gameType.getId())
                .numberOfDraws(1)
                .numbersAutogenerated(false)
                .mainNumbers(mainNumbers)
                .extraNumbers(null)
                .build();
        TicketResponseDto expectedResult = TicketMapper.toTicketResponseDto(ticketRequestDto);

        // when
        TicketResponseDto result = ticketServiceAdapter.addTicket(ticketRequestDto);

        // then
        assertAll(
                () -> assertThat(result).isNotNull(),
                () -> assertThat(result.gameTypeName()).isEqualTo(expectedResult.gameTypeName()),
                () -> assertThat(result.numberOfDraws()).isEqualTo(expectedResult.numberOfDraws()),
                () -> assertThat(result.numbers().getMainNumbers()).isEqualTo(expectedResult.numbers().getMainNumbers()),
                () -> assertThat(result.numbers().getExtraNumbers()).isEqualTo(expectedResult.numbers().getExtraNumbers())
        );
    }

    @Test
    void shouldReturnTicketResponseDtoListOfSpecificUser() {
        // given
        String userId = "some-user-id";
        TicketRequestDto ticketRequestDto;
        ticketRequestDto = TicketRequestDto.builder()
                .userId("")
                .gameTypeId(GameType.LOTTO.getId())
                .numberOfDraws(1)
                .numbersAutogenerated(true)
                .mainNumbers(List.of(1,2,3,4,5,6))
                .build();
        ticketRepositoryPort.save(TicketMapper.toTicket(ticketRequestDto));
        ticketRequestDto = TicketRequestDto.builder()
                .userId("some-other-user-id")
                .gameTypeId(GameType.LOTTO.getId())
                .numberOfDraws(1)
                .numbersAutogenerated(true)
                .mainNumbers(List.of(1,2,3,4,5,6))
                .build();
        ticketRepositoryPort.save(TicketMapper.toTicket(ticketRequestDto));
        ticketRequestDto = TicketRequestDto.builder()
                .userId(userId)
                .gameTypeId(GameType.LOTTO.getId())
                .numberOfDraws(1)
                .numbersAutogenerated(true)
                .mainNumbers(List.of(1,2,3,4,5,6))
                .build();
        ticketRepositoryPort.save(TicketMapper.toTicket(ticketRequestDto));
        ticketRequestDto = TicketRequestDto.builder()
                .userId(userId)
                .gameTypeId(GameType.LOTTO.getId())
                .numberOfDraws(1)
                .numbersAutogenerated(true)
                .mainNumbers(List.of(1,2,3,4,5,6))
                .build();
        ticketRepositoryPort.save(TicketMapper.toTicket(ticketRequestDto));

        // when
        List<TicketResponseDto> result = ticketServiceAdapter.getTicketsByUserId(userId);

        // then
        assertAll(
                () -> assertThat(result).isNotNull().hasSize(2),
                () -> assertThat(result.stream().map(TicketResponseDto::userId).toList()).containsOnly(userId)
        );
    }

}